name: Finalyze with SonarCloud
description: An opinionated action that analysis generated data and then uploads everything to SonarCloud.
inputs:
  token:
    description: The SonarCloud generated token.
    required: true
runs:
  using: composite
  steps:
    - name: SonarScanner for .NET
      run: >-
        dotnet sonarscanner end
        -d:sonar.token="${{ inputs.token }}"
      env:
        GITHUB_TOKEN: ${{ github.token }}
        SONAR_TOKEN: ${{ inputs.token }}
      shell: bash
branding:
  icon: 'umbrella'
  color: 'blue'
